const SentimentAnnotations = function() {

    this.characterSentiments = [
        "As expected most characters cluster around the neutral sentiment mark. The TV takes the prize for being the most positive. This is probably due to the repeated appearance of Bob Ross, the nicest person ever to appear on television. Jeff is an outlier in episode 5, but to be fair he had just a single line which was obviously not very complimentary.",
        "As usual most characters cluster around the neutral mark. Surpisingly Johnson comes across as quite positive in this series, but he really doesn't have as many lines as in other series. Pete from The Executioner's Bong is the most negative (episode 4) presumably because he bumps off Super Hans to get Jez to perform at the gig.",
        "As usual most characters cluster around the neutral mark. Both Sophie and Big Suze maintain a positive sentiment throughout the series. Jez is slightly more positive than Mark, especially in episodes 2 and 4 as he tries to gain favour with Merry and Sarah. The most surprising aspect of this series is not the sentiment, it's the fact that episode 4 only had 4 characters, which probably explains why that particular episode has the lowest number of lines in total out of all Peep Show episodes.",
        "As usual most characters cluster around the neutral mark. Sophie maintains a positive outlook, that is until the fateful jilting on the wedding day. Super Hans is an outlier during episode 1, but he only had a couple of lines. The same with Lisa in episode 2 as she joined the Project Zeus work group. Nancy remained positive throughout, the break in series 3 obviously did her good. Not even the Vicar's positive sentiment in episode 6 can save Mark and Sophie's wedding. Super Hans seems overly negative in episode 6 probably due to his massive hangover from the previous night.",
        "As expected most characters cluster around the neutral mark. Sophie's sentiment is much lower in this series as things begin to unravel after the wedding. Lisa is negative in episode 2 but this is because she tells Mark her thoughts on him jilting Sophie. Jeff is positive in episode 3 but he only has 3 lines. Jez is positive throughout except for episode 4 when he tries to play mind games with his new Dad after realising the money pipe is being cut off. Mark stays positive throughout surprisingly. He obviously moves on pretty quickly from the failed wedding.",
        "As expected most characters cluster around the neutral mark. The minor characters have the most negative and positive sentiments (see Others) but this is a tiny sample size so we can't read anything into that. Gail is extremely positive in episode 5 as she pops the question to Elena. Elena remains positive throughout the series, she's probably too self-centred to have any negative thoughts. Sentiment aside you can see this series had a lot of characters appear in it, especially in the party episode.",
        "As usual most characters cluster around the neutral mark. The main outliers are Zahra in episode 2 and Sophie in episode 4, although she hardly has any lines in this episode. In fact, Zahra remains positive throughout the series even though she could probably do better for herself in the romance department. Episode 1 is fairly positive on average as this is the episode where Sophie gives birth. The pizza delivery guy in episode 4 has the lowest sentiment average, probably due to him trying to deliver a pizza slice by slice through a letterbox. Ian, Sophie's Father, is also negative in that episode as he's disgusted with Mark for missing his son's christening. I was surprised to see Mark's Dad have a positive average sentiment, the sentiment analysis obviously didn't pick up on his veiled sarcasm.",
        "As expected most characters cluster around the neutral mark. In fact everyone is tightly clustered in this series without any real outliers. Johnson has the lowest sentiment in the series, his eulogy at Gerrard's funeral obviously didn't go down too well. Big Mad Andy has a negative sentiment in episode 4 as his life spirals out of control. Mark's highest sentiment average was in episode 2 as he manages to get his book \"published\".",
        "As usual most characters cluster around the neutral mark. We can see episode 2 is skewed towards a more positive sentiment, probably due to Molly and Super Hans' wedding. Episode 4 seems to skew toward a negative sentiment, probably all the talk of moles and such-like, plus the aborted bank job also occurs in this episode. Poor Megan goes through the mill in this series. She's struggling with life decisions only to be given false hope from life coach Jez with catastrophic results. By episode 4 her hatred for Jez really comes through. Johnson's sentiment is fairly negative throughout as he tries to run a tight ship in the bank. Angus and April remain positive despite their marital problems, they are obviously just too nice for it to affect how they deal with others."
    ]
}

export default SentimentAnnotations;