const SentimentAnnotations = function() {

    this.characterSentiments = [
        "As expected most characters cluster around the neutral sentiment mark. The TV takes the prize for being the most positive. This is probably due to the repeated appearance of Bob Ross, the nicest person ever to appear on television. Jeff is an outlier in episode 5, but to be fair he had just a single line which was obviously not very complimentary. I was surprised to see that the gang of local youths had a positive sentiment in the first episode. This is probably due to them complimenting Mark's clean shirt. You can just make out a positive trend as the episodes progress, up until the final episode where the funeral brings it back down.",
        "Again we see a clustering around the neutral mark although the first episode shows a definite positive skew with, surprisingly, Johnson way out on top courtesy of his pep talk at JLB. We also see other positive outliers but they are mainly the minor characters like Tony, Nim and the registrar from Jez's sham wedding who only had a couple of lines each. Pete from The Executioner's Bong is the most negative (episode 4) presumably because he bumps off Super Hans to get Jez to perform at the gig.",
        "This series is slightly more positive than the first two as you can see clustering just above the neutral mark. Both Sophie and Big Suze maintain a positive sentiment throughout the series. Jez is slightly more positive than Mark, especially in episodes 2 and 4 as he tries to gain favour with Merry and Sarah. Jeff is the big outlier here but again it's a small sample size, his only line being his opinion of Colin Cooper, obviously it isn't very complimentary. The most surprising aspect of this chart is the fact that episode 4 only had 4 characters! This probably explains why that particular episode has the lowest number of lines out of the entire Peep Show oeuvre.",
        "As usual most characters cluster around the neutral mark. Sophie maintains a positive outlook, that is until the fateful jilting on the wedding day. Super Hans goes through the entire gamut of human emotions in this series from very positive in episode 1 (although he only had a couple of lines) to negative in the final episode, probably due to his massive hangover on Mark's wedding day. Lisa is a positive outlier in episode 2 as she joined the Project Zeus work group and got out before Mark turned into the worst boss in human history. Nancy remained positive throughout, the break in series 3 obviously did her good. Not even the Vicar's positive sentiment in episode 6 can save Mark and Sophie's wedding. I think the driver's negative sentiment in the final episode can be excused as he wouldn't have known that Mark was trying to get run over on purpose to avoid getting married.",
        "As expected most characters cluster around the neutral mark. Sophie's sentiment starts off much lower in this series as she deals with the post wedding fiasco. Lisa is the most negative person in the series, this is due to episode 2 where she tells Mark her thoughts on him jilting Sophie. Jeff veers from one extreme to the other due to only having a very few lines in this series. Jez is positive throughout except for episode 4 due to him being incredibly rude to his Mum and trying to play mind games with his new Dad after realising the money pipe is being cut off. Mark stays positive throughout surprisingly. He obviously moves on pretty quickly from the failed wedding.",
        "As expected most characters cluster around the neutral mark but there are some positive outliers, particularly Gail in episode 5. This is the party episode where she proposes to Elena which explains that. The minor characters covered under \"Others\" are also outliers but this is a very small sample size. The negative sentiment in episode 1 comes from a security guard at JLB warning everyone about a fire alarm and the positive sentiment in episode 6 comes from the instructor during Mark's driving test. Elena remains positive throughout the series, she's probably too self-centred to have any negative thoughts. Dobby is quite negative in episode 2 as she finally finds out why Mark is acting strangely. Another negative character is the Tourist from episode 3. This is the guy heckling Mark during his Jack The Ripper tour. Sentiment aside you can see this series had a lot of characters appear in it, especially in the party episode as Mark finally manages to arrange a social gathering.",
        "As usual most characters cluster around the neutral mark but overall we do see it skewing slightly to the positive side, maybe because we have episodes with happier themes such as a new baby, Christmas and New Year's Eve. We can see a couple of positive outliers, Zahra in episode 2 and Sophie in episode 4, although they don't have many lines in these episodes. In fact, Zahra remains positive throughout the series even though she could probably do better for herself in the romance department. Episode 1 is fairly positive on average as this is the episode where Sophie gives birth and we can see most of the hospital staff are being kind, except for the theatre nurse who's probably negative as she warns Mark not to look at the \"goal end\". I was surprised to see the door-to-door seller from episode 3 in neutral sentiment territory, obviously his meekness trying to flog expensive feather dusters helped balance out his aggression when Mark brings him the wrong order at Banditos. The pizza delivery guy in episode 4 has the lowest sentiment average, probably due to him trying to deliver a pizza slice by slice through a letterbox. Ian, Sophie's Father, is also negative in that episode as he's disgusted with Mark for missing his son's christening. I was also surprised to see Mark's Dad come out with a positive average, the sentiment analysis obviously didn't pick up on his thinly veiled sarcasm.",
        "Just as in the previous series we see a slight trend towards an overall positive sentiment. Again we see positive outliers for minor characters and characters with very few lines (Neil in episode 6). The positive \"Others\" in the first two episodes mainly come from Mark's interview rivals at Baths, Bathrooms and Fittings, the Vicar at Gerrard's funeral and a waitress at a café. Johnson has the lowest sentiment in the series, his eulogy at Gerrard's funeral obviously didn't go down too well. Big Mad Andy has a negative sentiment in episode 4 as his life spirals out of control and Jez becomes his only hope. He seems to recover in episode 5 but this is only because he offers Jez a corner and a bin bag to sleep in. Mark's highest sentiment average was in episode 2 as he manages to get his book \"published\". Super Hans' sentiment is up and down as he becomes Mark's boss, loses it during paintballing, and tries to engineer his love life via the classified ads.",
        "We see clustering around the neutral mark as before but episode 2 is clearly more positive, probably due to it being Super Hans and Molly's wedding. Only Gregory's aggression, Dobby's lament over her and Mark's past and the driver Frank, who to be fair thought he was going to be murdered, bring it down. Poor Megan goes through the mill in this series. She's struggling with life decisions only to be given false hope from life coach Jez with catastrophic results. By episode 4 her hatred for Jez really shows. Angus and April remain positive despite their marital problems, they are obviously just too nice for it to affect how they deal with others. The minor characters under \"Others\" are again outliers due to the small number of lines that they have. It dips from positive (the registrar at Super Hans and Molly's wedding) to negative (the TV in the very last episode delcaring that wolves have been reintroduced)."
    ]
}

export default SentimentAnnotations;