const ReferenceData = function() {
    this.episodeTitles = [
        "Warring Factions",
        "The Interview",
        "On the Pull",
        "Mark Makes a Friend",
        "Dream Job",
        "Funeral",
        "Dance Class",
        "Jeremy Makes It",
        "Local Zero",
        "University Challenge",
        "The Man Show",
        "Wedding",
        "Mugging",
        "Sectioning",
        "Shrooming",
        "Sistering",
        "Jurying",
        "Quantocking",
        "Sophie's Parents",
        "Conference",
        "Gym",
        "Handyman",
        "Holiday",
        "The Wedding",
        "Burgling",
        "Spin War",
        "Jeremy Broke",
        "Jeremy's Mummy",
        "Jeremy's Manager",
        "Mark's Women",
        "Jeremy at JLB",
        "The Test",
        "Jeremy in Love",
        "The Affair",
        "The Party",
        "Das Boot",
        "St Hospitals",
        "Man Jam",
        "A Beautiful Mind",
        "Nether Zone",
        "Seasonal Beatings",
        "New Year's Eve",
        "Jeremy Therapised",
        "Business Secrets of the Pharaohs",
        "The Love Bunker",
        "Big Mad Andy",
        "Chairman Mark",
        "Quantocking II",
        "The William Morris Years",
        "Gregory's Beard",
        "Threeism",
        "Mole-Mapping",
        "Kid Farm",
        "Are We Going To Be Alright?"
    ];
}

export default ReferenceData;